<?php
/**
 * @file
 * Contains ddd_forms_talk.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ddd_forms_talk_help($route_name, RouteMatchInterface $route_match) {
  $output = '';
  switch ($route_name) {
    // Main module help for the ddd_forms_talk module.
    case 'help.page.ddd_forms_talk':
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is a demonstration module for my talk on Drupal 8 Forms, at the Drupal development Days in Milan - 2016') . '</p>';

    default:
  }
  return $output;
}

/**
 * Implements hook_theme().
 */
function ddd_forms_talk_theme($existing, $type, $theme, $path) {
  return [
    'ddd_forms_talk_form_submission' => [
      'variables' => [
        'submitted_data' => [],
      ],
      'template' => 'ddd-forms-talk-form-submission',
    ],
  ];
}
